services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /home/lobon/Documents/wolfon/database
    volumes:
      - pgdata:/home/lobon/Documents/wolfon/database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: