### create card
POST 127.0.0.1:80/cards/
Content-Type: application/json

{
  "user_id": "68851b297b4e024b3a91b77b",
  "title": "Visa",
  "gastos": 1234.5
}

<> 2025-07-19T191045.201.json


### create cards from an excel xlsx
POST 127.0.0.1:80/cards/import/file?user_id=68851b297b4e024b3a91b77b
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test1.xlsx"
Content-Type: multipart/form-data

< ../test_docs/test1.xlsx
--WebAppBoundary--

### create cards from an excel xls
POST 127.0.0.1:80/cards/import/file?user_id=68851b297b4e024b3a91b77b
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test1.xlsx"
Content-Type: multipart/form-data

< ../test_docs/test1.xls
--WebAppBoundary--

### create cards from an excel ods
POST 127.0.0.1:80/cards/import/file?user_id=68851b297b4e024b3a91b77b
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test1.xlsx"
Content-Type: multipart/form-data

< ../test_docs/test1.ods
--WebAppBoundary--


### Export user cards
GET 127.0.0.1:80/users/export_cards/68851b297b4e024b3a91b77b


### get card
GET 127.0.0.1:80/cards/688520351927a530cb24a104

<> 2025-07-19T191121.200.json



### update card
PUT 127.0.0.1:80/cards/
Content-Type: application/json

{
  "_id": "688520351927a530cb24a104",
  "ingresos": "5432.1"
}


### delete card
DELETE 127.0.0.1:80/cards/687c0429adfdc4d462d68f03

<> 2025-07-19T180413.404.json


### Search
GET 127.0.0.1:80/<database>/<field>?<value>