### Create User 1
POST 127.0.0.1:80/users/
Content-Type: application/json

{
  "name": "Fulano de tal",
  "email": "fulano.detal@wolfon.com"
}


### subscribe user
POST 127.0.0.1:80/users/subscribe/
Content-Type: application/json

{
  "user_id": "68851b297b4e024b3a91b77b",
  "tier": "standard"
}

### get user
GET 127.0.0.1:80/users/68851b297b4e024b3a91b77b


### check sub
GET 127.0.0.1:80/users/check_subscription/68851b297b4e024b3a91b77b

### cancel sub
GET 127.0.0.1:80/users/cancel_subscription/68851b297b4e024b3a91b77b

### renew sub
GET 127.0.0.1:80/users/renew_subscription/68851b297b4e024b3a91b77b


### En los comandos de listado por defecto size=10 y page=1
### list users
GET 127.0.0.1:80/users/list


### list cards
GET 127.0.0.1:80/users/list_cards/68851b297b4e024b3a91b77b



### update users
PUT 127.0.0.1:80/users/
Content-Type: application/json

{
  "_id": "68851b297b4e024b3a91b77b",
  "position": "CEO",
  "salary": 1234.2
}

### delete users
#DELETE 127.0.0.1:80/users/68851b297b4e024b3a91b77b